;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2025 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-69                      |
; |                             hi@hex-rays.com                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 047B912EE0F8247F3FB43CF0DD42A0F43D728EF07A2E9DF774FD8326AEF1CE2B
; Input MD5    : 20BFD2EDC7CB9E8D0A0DD66F47C658EB
; Input CRC32  : D5038A6F
; Compiler     : GNU C++

; File Name   : /mnt/shanes-ssd-1tb/code/shane/auto-re/autore-reconstruction/tests/fixtures/hello
; Format      : ELF64 for x86-64 (Executable)
; Imagebase   : 400000
; Interpreter '/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67/lib/ld-linux-x86-64.so.2'
; Needed Library 'libc.so.6'
; Library runpath '/nix/store/x7g21yqr2wgrjjiwxxibn371lgjy6i6h-devenv-shell-env/lib:/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67/lib:/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib/lib'
;
; Source File : 'crt1.o'
; Source File : 'hello.c'
; Source File : 'crtbegin.o'
; Source File : 'crtend.o'

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 400000h
dword_400000    dd 464C457Fh            ; DATA XREF: LOAD:00000000004000C0↓o
                                        ; File format: \x7FELF
                db 2                    ; File class: 64-bit
                db 1                    ; Data encoding: little-endian
                db 1                    ; File version
                db 0                    ; OS/ABI: UNIX System V ABI
                db 0                    ; ABI Version
                db 7 dup(0)             ; Padding
                dw 2                    ; File type: Executable
                dw 3Eh                  ; Machine: x86-64
                dd 1                    ; File version
                dq offset _start        ; Entry point
                dq 40h                  ; PHT file offset
                dq 3660h                ; SHT file offset
                dd 0                    ; Processor-specific flags
                dw 40h                  ; ELF header size
                dw 38h                  ; PHT entry size
                dw 0Dh                  ; Number of entries in PHT
                dw 40h                  ; SHT entry size
                dw 1Dh                  ; Number of entries in SHT
                dw 1Ch                  ; SHT entry index for string table
; ELF64 Program Header
; PHT Entry 0
dword_400040    dd 6                    ; DATA XREF: LOAD:0000000000400050↓o
                                        ; Type: PHDR
                dd 4                    ; Flags
                dq 40h                  ; File offset
                dq offset dword_400040  ; Virtual address
                dq 400040h              ; Physical address
                dq 2D8h                 ; Size in file image
                dq 2D8h                 ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 1
                dd 3                    ; Type: INTERP
                dd 4                    ; Flags
                dq 318h                 ; File offset
                dq offset aNixStore8kvxvr ; Virtual address
                dq 400318h              ; Physical address
                dq 53h                  ; Size in file image
                dq 53h                  ; Size in memory image
                dq 1                    ; Alignment
; PHT Entry 2
                dd 1                    ; Type: LOAD
                dd 4                    ; Flags
                dq 0                    ; File offset
                dq offset dword_400000  ; Virtual address
                dq 400000h              ; Physical address
                dq 5A8h                 ; Size in file image
                dq 5A8h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 3
                dd 1                    ; Type: LOAD
                dd 5                    ; Flags
                dq 1000h                ; File offset
                dq offset _init_proc    ; Virtual address
                dq 401000h              ; Physical address
                dq 1B5h                 ; Size in file image
                dq 1B5h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 4
                dd 1                    ; Type: LOAD
                dd 4                    ; Flags
                dq 2000h                ; File offset
                dq offset _IO_stdin_used ; Virtual address
                dq 402000h              ; Physical address
                dq 190h                 ; Size in file image
                dq 190h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 5
                dd 1                    ; Type: LOAD
                dd 6                    ; Flags
                dq 2DB0h                ; File offset
                dq offset __frame_dummy_init_array_entry ; Virtual address
                dq 403DB0h              ; Physical address
                dq 260h                 ; Size in file image
                dq 268h                 ; Size in memory image
                dq 1000h                ; Alignment
; PHT Entry 6
                dd 2                    ; Type: DYNAMIC
                dd 6                    ; Flags
                dq 2DC0h                ; File offset
                dq offset _DYNAMIC      ; Virtual address
                dq 403DC0h              ; Physical address
                dq 210h                 ; Size in file image
                dq 210h                 ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 7
                dd 4                    ; Type: NOTE
                dd 4                    ; Flags
                dq 2130h                ; File offset
                dq offset dword_402130  ; Virtual address
                dq 402130h              ; Physical address
                dq 40h                  ; Size in file image
                dq 40h                  ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 8
                dd 4                    ; Type: NOTE
                dd 4                    ; Flags
                dq 2170h                ; File offset
                dq offset __abi_tag     ; Virtual address
                dq 402170h              ; Physical address
                dq 20h                  ; Size in file image
                dq 20h                  ; Size in memory image
                dq 4                    ; Alignment
; PHT Entry 9
                dd 6474E553h            ; Type: 6474E553
                dd 4                    ; Flags
                dq 2130h                ; File offset
                dq offset dword_402130  ; Virtual address
                dq 402130h              ; Physical address
                dq 40h                  ; Size in file image
                dq 40h                  ; Size in memory image
                dq 8                    ; Alignment
; PHT Entry 10
                dd 6474E550h            ; Type: EH_FRAME
                dd 4                    ; Flags
                dq 2018h                ; File offset
                dq offset __GNU_EH_FRAME_HDR ; Virtual address
                dq 402018h              ; Physical address
                dq 44h                  ; Size in file image
                dq 44h                  ; Size in memory image
                dq 4                    ; Alignment
; PHT Entry 11
                dd 6474E551h            ; Type: STACK
                dd 6                    ; Flags
                dq 0                    ; File offset
                dq 0                    ; Virtual address
                dq 0                    ; Physical address
                dq 0                    ; Size in file image
                dq 0                    ; Size in memory image
                dq 10h                  ; Alignment
; PHT Entry 12
                dd 6474E552h            ; Type: RO-AFTER
                dd 4                    ; Flags
                dq 2DB0h                ; File offset
                dq offset __frame_dummy_init_array_entry ; Virtual address
                dq 403DB0h              ; Physical address
                dq 250h                 ; Size in file image
                dq 250h                 ; Size in memory image
                dq 1                    ; Alignment
aNixStore8kvxvr db '/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67/lib/ld-'
                                        ; DATA XREF: LOAD:0000000000400088↑o
                db 'linux-x86-64.so.2',0
                align 10h
; ELF Hash Table
elf_hash_nbucket dd 3
elf_hash_nchain dd 4
elf_hash_bucket dd 2, 1, 3
elf_hash_chain  dd 4 dup(0)
                align 8
; ELF GNU Hash Table
elf_gnu_hash_nbuckets dd 1
elf_gnu_hash_symbias dd 1
elf_gnu_hash_bitmask_nwords dd 1
elf_gnu_hash_shift dd 0
elf_gnu_hash_indexes dq 0
elf_gnu_hash_bucket dd 0
elf_gnu_hash_chain dd 0
; ELF Symbol Table
                Elf64_Sym <0>
                Elf64_Sym <offset aLibcStartMain - offset byte_400418, 12h, 0, 0, 0, \ ; "__libc_start_main"
                           0>
                Elf64_Sym <offset aGmonStart - offset byte_400418, 20h, 0, 0, 0, 0> ; "__gmon_start__"
                Elf64_Sym <offset aPrintfChk - offset byte_400418, 12h, 0, 0, 0, 0> ; "__printf_chk"
; ELF String Table
byte_400418     db 0                    ; DATA XREF: LOAD:00000000004003D0↑o
                                        ; LOAD:00000000004003E8↑o ...
aPrintfChk      db '__printf_chk',0     ; DATA XREF: LOAD:0000000000400400↑o
aLibcStartMain  db '__libc_start_main',0 ; DATA XREF: LOAD:00000000004003D0↑o
aLibcSo6        db 'libc.so.6',0        ; DATA XREF: LOAD:0000000000400530↓o
aGlibc234       db 'GLIBC_2.3.4',0      ; DATA XREF: LOAD:0000000000400540↓o
aGlibc234_0     db 'GLIBC_2.34',0       ; DATA XREF: LOAD:0000000000400550↓o
aNixStoreX7g21y db '/nix/store/x7g21yqr2wgrjjiwxxibn371lgjy6i6h-devenv-shell-env/lib:'
                db '/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67/lib:/ni'
                db 'x/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib/lib',0
aGmonStart      db '__gmon_start__',0   ; DATA XREF: LOAD:00000000004003E8↑o
; ELF GNU Symbol Version Table
                dw 0
                dw 2                    ; __libc_start_main@@GLIBC_2.34
                dw 0                    ; local  symbol: __gmon_start__
                dw 3                    ; __printf_chk@@GLIBC_2.3.4
                dw 0
; ELF GNU Symbol Version Requirements
                Elf64_Verneed <1, 2, offset aLibcSo6 - offset byte_400418, 10h, 0> ; "libc.so.6"
                Elf64_Vernaux <9691974h, 0, 3, offset aGlibc234 - offset byte_400418, \ ; "GLIBC_2.3.4"
                               10h>
                Elf64_Vernaux <69691B4h, 0, 2, \ ; "GLIBC_2.34"
                               offset aGlibc234_0 - offset byte_400418, 0>
; ELF RELA Relocation Table
                Elf64_Rela <403FF0h, 100000006h, 0> ; R_X86_64_GLOB_DAT __libc_start_main
                Elf64_Rela <403FF8h, 200000006h, 0> ; R_X86_64_GLOB_DAT __gmon_start__
; ELF JMPREL Relocation Table
                Elf64_Rela <403FE8h, 300000007h, 0> ; R_X86_64_JUMP_SLOT __printf_chk
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_init           segment dword public 'CODE' use64
                assume cs:_init
                ;org 401000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Alternative name is '_init'

                public _init_proc
_init_proc      proc near               ; DATA XREF: LOAD:00000000004000F8↑o
                endbr64
                sub     rsp, 8
                mov     rax, cs:__gmon_start___ptr
                test    rax, rax
                jz      short loc_401016
                call    rax ; __gmon_start__

loc_401016:                             ; CODE XREF: _init_proc+12↑j
                add     rsp, 8
                retn
_init_proc      endp

_init           ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD            segment mempage public 'CODE' use64
                assume cs:LOAD
                ;org 40101Bh
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                align 20h
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_plt            segment para public 'CODE' use64
                assume cs:_plt
                ;org 401020h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================


sub_401020      proc near               ; CODE XREF: .plt:000000000040103B↓j
; __unwind {
                push    cs:qword_403FD8
                jmp     cs:qword_403FE0
sub_401020      endp

; ---------------------------------------------------------------------------
                align 10h
; [00000006 BYTES: COLLAPSED FUNCTION ___printf_chk]
; ---------------------------------------------------------------------------
                push    0
                jmp     sub_401020
; } // starts at 401020
_plt            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment para public 'CODE' use64
                assume cs:_text
                ;org 401040h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

; int __fastcall main(int argc, const char **argv, const char **envp)
                public main
main            proc near               ; DATA XREF: _start+18↓o
; __unwind {
                push    rbp
                mov     esi, 2
                mov     edi, 1
                mov     rbp, rsp
                push    r12
                push    rbx
                call    add
                mov     esi, 4
                mov     edi, 3
                mov     ebx, eax
                call    multiply
                lea     rdi, aWorld     ; "world"
                mov     r12d, eax
                call    greet
                lea     eax, [rbx+r12]
                pop     rbx
                pop     r12
                pop     rbp
                retn
; } // starts at 401040
main            endp

; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn fuzzy-sp

                public _start
_start          proc near               ; DATA XREF: LOAD:0000000000400018↑o
; __unwind {
                endbr64
                xor     ebp, ebp
                mov     r9, rdx         ; rtld_fini
                pop     rsi             ; argc
                mov     rdx, rsp        ; ubp_av
                and     rsp, 0FFFFFFFFFFFFFFF0h
                push    rax
                push    rsp             ; stack_end
                xor     r8d, r8d        ; fini
                xor     ecx, ecx        ; init
                mov     rdi, offset main ; main
                call    cs:__libc_start_main_ptr
                hlt
; } // starts at 401080
_start          endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


                public _dl_relocate_static_pie
_dl_relocate_static_pie proc near
; __unwind {
                endbr64
                retn
; } // starts at 4010B0
_dl_relocate_static_pie endp

; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================


deregister_tm_clones proc near          ; CODE XREF: __do_global_dtors_aux+11↓p
                mov     eax, offset __TMC_END__
                cmp     rax, offset __TMC_END__
                jz      short locret_4010E0
                mov     eax, 0
                test    rax, rax
                jz      short locret_4010E0
                mov     edi, offset __TMC_END__
                jmp     rax
; ---------------------------------------------------------------------------
                align 20h

locret_4010E0:                          ; CODE XREF: deregister_tm_clones+B↑j
                                        ; deregister_tm_clones+15↑j
                retn
deregister_tm_clones endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


register_tm_clones proc near            ; CODE XREF: frame_dummy+4↓j
                mov     esi, offset __TMC_END__
                sub     rsi, offset __TMC_END__
                mov     rax, rsi
                shr     rsi, 3Fh
                sar     rax, 3
                add     rsi, rax
                sar     rsi, 1
                jz      short locret_401120
                mov     eax, 0
                test    rax, rax
                jz      short locret_401120
                mov     edi, offset __TMC_END__
                jmp     rax
; ---------------------------------------------------------------------------

locret_401120:                          ; CODE XREF: register_tm_clones+1D↑j
                                        ; register_tm_clones+27↑j
                retn
register_tm_clones endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


__do_global_dtors_aux proc near         ; DATA XREF: .fini_array:__do_global_dtors_aux_fini_array_entry↓o
                endbr64
                cmp     cs:__TMC_END__, 0
                jnz     short locret_401150
                push    rbp
                mov     rbp, rsp
                call    deregister_tm_clones
                mov     cs:__TMC_END__, 1
                pop     rbp
                retn
; ---------------------------------------------------------------------------
                align 10h

locret_401150:                          ; CODE XREF: __do_global_dtors_aux+B↑j
                retn
__do_global_dtors_aux endp

; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================


frame_dummy     proc near               ; DATA XREF: .init_array:__frame_dummy_init_array_entry↓o
                endbr64
                jmp     short register_tm_clones
frame_dummy     endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


                public add
add             proc near               ; CODE XREF: main+11↑p
; __unwind {
                lea     eax, [rdi+rsi]
                xor     esi, esi
                xor     edi, edi
                retn
; } // starts at 401170
add             endp

; ---------------------------------------------------------------------------
                align 20h

; =============== S U B R O U T I N E =======================================


                public multiply
multiply        proc near               ; CODE XREF: main+22↑p
; __unwind {
                mov     eax, edi
                imul    eax, esi
                xor     esi, esi
                xor     edi, edi
                retn
; } // starts at 401180
multiply        endp

; ---------------------------------------------------------------------------
                align 10h

; =============== S U B R O U T I N E =======================================


                public greet
greet           proc near               ; CODE XREF: main+31↑p
; __unwind {
                mov     rdx, rdi
                lea     rsi, aHelloS    ; "Hello, %s!\n"
                mov     edi, 2
                xor     eax, eax
                jmp     ___printf_chk
; } // starts at 401190
greet           endp

_text           ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD            segment mempage public 'CODE' use64
                assume cs:LOAD
                ;org 4011A6h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                align 8
LOAD            ends

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_fini           segment dword public 'CODE' use64
                assume cs:_fini
                ;org 4011A8h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Alternative name is '_fini'

                public _term_proc
_term_proc      proc near
                endbr64
                sub     rsp, 8
                add     rsp, 8
                retn
_term_proc      endp

_fini           ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_rodata         segment dword public 'CONST' use64
                assume cs:_rodata
                ;org 402000h
                public _IO_stdin_used
_IO_stdin_used  db 1, 0, 2, 0           ; DATA XREF: LOAD:0000000000400130↑o
aHelloS         db 'Hello, %s!',0Ah,0   ; DATA XREF: greet+3↑o
aWorld          db 'world',0            ; DATA XREF: main+27↑o
_rodata         ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 402016h
                align 8
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_eh_frame_hdr   segment dword public 'CONST' use64
                assume cs:_eh_frame_hdr
                ;org 402018h
__GNU_EH_FRAME_HDR dq 443B031B01h, 0FFFFF00800000007h, 0FFFFF02800000088h
                                        ; DATA XREF: LOAD:0000000000400280↑o
                dq 0FFFFF068000000ECh, 0FFFFF09800000060h, 0FFFFF15800000074h
                dq 0FFFFF168000000B0h, 0FFFFF178000000C4h
                db 0D8h, 3 dup(0)
_eh_frame_hdr   ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 40205Ch
                align 20h
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_eh_frame       segment qword public 'CONST' use64
                assume cs:_eh_frame
                ;org 402060h
                dq 14h, 110780100527A01h, 19008070C1Bh, 1C00000010h, 26FFFFF000h
                dq 1010074400h, 0FFFFF01C00000030h, 5, 4400000024h, 20FFFFEF78h
                dq 0F4A180E46100E00h, 3B1A3F008008770Bh, 2224332Ah, 6C00000010h
                dq 8FFFFF0A0h, 1000000000h, 0FFFFF09C00000080h, 0Ah, 9400000010h
                dq 16FFFFF098h, 2000000000h, 0FFFFEF34000000A8h, 100E41000000003Fh
                dq 38C43060D4D0286h, 8070C6D0483h
__FRAME_END__   db 4 dup(0)
_eh_frame       ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 40212Ch
                align 10h
; ELF Note Entry
dword_402130    dd 4                    ; DATA XREF: LOAD:00000000004001D8↑o
                                        ; LOAD:0000000000400248↑o
                                        ; Name Size
                dd 30h                  ; Desc Size
                dd 5                    ; Type: NT_GNU_PROPERTY_TYPE_0
aGnu            db 'GNU',0              ; Name
                db 2, 80h, 0, 0C0h, 4, 3 dup(0), 1, 7 dup(0), 1, 0, 1 ; Desc
                db 0C0h, 4, 3 dup(0), 1, 7 dup(0), 2, 0, 1, 0C0h, 4, 3 dup(0)
                db 1, 7 dup(0)
; ELF Note Entry
__abi_tag       dd 4                    ; DATA XREF: LOAD:0000000000400210↑o
                                        ; Name Size
                dd 10h                  ; Desc Size
                dd 1                    ; Type: NT_GNU_ABI_TAG
aGnu_0          db 'GNU',0              ; Name
                dd 0, 3, 0Ah, 0         ; ABI: Linux 3.10.0
LOAD            ends

; ELF Initialization Function Table
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_init_array     segment qword public 'DATA' use64
                assume cs:_init_array
                ;org 403DB0h
__frame_dummy_init_array_entry dq offset frame_dummy
                                        ; DATA XREF: LOAD:0000000000400168↑o
                                        ; LOAD:00000000004002F0↑o
_init_array     ends

; ELF Termination Function Table
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_fini_array     segment qword public 'DATA' use64
                assume cs:_fini_array
                ;org 403DB8h
__do_global_dtors_aux_fini_array_entry dq offset __do_global_dtors_aux
_fini_array     ends

; ELF Dynamic Information
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
LOAD            segment mempage public 'DATA' use64
                assume cs:LOAD
                ;org 403DC0h
_DYNAMIC        Elf64_Dyn <1, 20h>      ; DATA XREF: LOAD:00000000004001A0↑o
                                        ; .got:_GLOBAL_OFFSET_TABLE_↓o
                                        ; DT_NEEDED libc.so.6
                Elf64_Dyn <1Dh, 41h>    ; DT_RUNPATH /nix/store/x7g21yqr2wgrjjiwxxibn371lgjy6i6h-devenv-shell-env/lib:/nix/store/8kvxvr3pmsypxiypq4g8zy13glnfr7nx-glibc-2.42-67/lib:/nix/store/hngmi01i8wgi25a0byrxcn4ysz5j79mw-gcc-15.2.0-lib/lib
                Elf64_Dyn <0Ch, 401000h> ; DT_INIT
                Elf64_Dyn <0Dh, 4011A8h> ; DT_FINI
                Elf64_Dyn <19h, 403DB0h> ; DT_INIT_ARRAY
                Elf64_Dyn <1Bh, 8>      ; DT_INIT_ARRAYSZ
                Elf64_Dyn <1Ah, 403DB8h> ; DT_FINI_ARRAY
                Elf64_Dyn <1Ch, 8>      ; DT_FINI_ARRAYSZ
                Elf64_Dyn <4, 400370h>  ; DT_HASH
                Elf64_Dyn <6FFFFEF5h, 400398h> ; DT_GNU_HASH
                Elf64_Dyn <5, 400418h>  ; DT_STRTAB
                Elf64_Dyn <6, 4003B8h>  ; DT_SYMTAB
                Elf64_Dyn <0Ah, 10Eh>   ; DT_STRSZ
                Elf64_Dyn <0Bh, 18h>    ; DT_SYMENT
                Elf64_Dyn <15h, 0>      ; DT_DEBUG
                Elf64_Dyn <3, 403FD0h>  ; DT_PLTGOT
                Elf64_Dyn <2, 18h>      ; DT_PLTRELSZ
                Elf64_Dyn <14h, 7>      ; DT_PLTREL
                Elf64_Dyn <17h, 400590h> ; DT_JMPREL
                Elf64_Dyn <7, 400560h>  ; DT_RELA
                Elf64_Dyn <8, 30h>      ; DT_RELASZ
                Elf64_Dyn <9, 18h>      ; DT_RELAENT
                Elf64_Dyn <1Eh, 8>      ; DT_FLAGS
                Elf64_Dyn <6FFFFFFBh, 1> ; DT_FLAGS_1
                Elf64_Dyn <6FFFFFFEh, 400530h> ; DT_VERNEED
                Elf64_Dyn <6FFFFFFFh, 1> ; DT_VERNEEDNUM
                Elf64_Dyn <6FFFFFF0h, 400526h> ; DT_VERSYM
                Elf64_Dyn <0>           ; DT_NULL
                dq 0Ah dup(0)
LOAD            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_got            segment qword public 'DATA' use64
                assume cs:_got
                ;org 403FD0h
_GLOBAL_OFFSET_TABLE_ dq offset _DYNAMIC
qword_403FD8    dq 0                    ; DATA XREF: sub_401020↑r
qword_403FE0    dq 0                    ; DATA XREF: sub_401020+6↑r
__printf_chk_ptr dq offset __printf_chk ; DATA XREF: ___printf_chk↑r
__libc_start_main_ptr dq offset __libc_start_main ; DATA XREF: _start+1F↑r
__gmon_start___ptr dq offset __gmon_start__ ; DATA XREF: _init_proc+8↑r
_got            ends

; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment qword public 'DATA' use64
                assume cs:_data
                ;org 404000h
                public __data_start
__data_start    dq 0
                public __dso_handle
__dso_handle    dq 0
_data           ends

; ===========================================================================

; Segment type: Uninitialized
; Segment permissions: Read/Write
_bss            segment byte public 'BSS' use64
                assume cs:_bss
                ;org 404010h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
                public __TMC_END__
__TMC_END__     db ?                    ; DATA XREF: deregister_tm_clones↑o
                                        ; deregister_tm_clones+5↑o ...
                                        ; Alternative name is 'completed.0'
                                        ; Alternative name is '_edata'
                                        ; Alternative name is '__bss_start'
                align 8
_bss            ends

; ===========================================================================

; Segment type: Zero-length
_prgend         segment byte public '' use64
_end            label byte
_prgend         ends

; ===========================================================================

; Segment type: Externs
; extern
; int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end)
                extrn __libc_start_main:near ; CODE XREF: _start+1F↑p
                                        ; DATA XREF: .got:__libc_start_main_ptr↑o
                extrn __printf_chk:near ; CODE XREF: ___printf_chk↑j
                                        ; DATA XREF: .got:__printf_chk_ptr↑o
                extrn __gmon_start__:near ; weak ; CODE XREF: _init_proc+14↑p
                                        ; DATA XREF: .got:__gmon_start___ptr↑o


                end _start
